version: "3.8"

services:
  app:
    env_file:
      - ./.env
    container_name: app-dev
    image: app-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 8080:8080